name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Java y html5validator
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jre python3-pip
          pip install html5validator

      - name: Validar HTML
        run: html5validator --root .

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Mostrar archivos subidos (para debug)
        run: ls -la

      - name: Subir archivos a GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

      - name: Publicar en GitHub Pages
        uses: actions/deploy-pages@v3
