name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  validate-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout del código
        uses: actions/checkout@v3

      - name: Validar el código
        uses: Cyber-Jak3/html5-validator-action@v1
        with:
          files: 'index.html'

  deploy:
    needs: validate-code
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Subir a GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

      - name: Publicar en GitHub Pages
        uses: actions/deploy-pages@v3
